spring.application.name=api-service

# # Configuration for the H2 database
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


# Configuration for the MySQL database
spring.datasource.url=jdbc:mysql://localhost:3306/java_project
spring.datasource.username=spring
spring.datasource.password=motdepasse123
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# # Configuration for the PostgreSQL database
# spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # SECRET KEY for JWT
jwt.secret=qXIhdtpKEyrq2ebQEV4fcA/kQwDui0ZJFUnvvkD3vfyko2y+/srdMOwkrhaufVHo
jwt.expiration=86400000
